version: '3.3'

services:
  db:
    image: mysql:8.0.19
    command: 'default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=mohammad
      - MYSQL_PASSWORD=pasha2905
    expose:
      - "3306"
      - "33060"

  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=mohammad
      - WORDPRESS_DB_PASSWORD=pasha2905
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - db

volumes: 
  db_data:
